#!/bin/bash

##Merge counts from all samples into single file
exec >> scripts/get_counts.log
exec 2>&1

ml R/4.1.2-foss-2020b

cd "$1"

#File format of counts.tsv generated by STAR
#column1: gene id
#column2: unstranded
#column3: 1st strand
#column4: 2nd strand

for file in */STAR; do
	samp=$(dirname $(echo $file))

	#Change value of cut -f1,x based on strand information
	cat ${file}/ReadsPerGene.out.tab | cut -f1,2 > ${samp}/counts.tsv
	line=$(echo -e "geneid\t${samp}")
	sed -i "1s/^/${line}\n/" ${samp}/counts.tsv
done

R --no-save << RSCRIPT
library(readr)
library(plyr)
samples <- paste0(dir(),"/counts.tsv")
samples <- samples[file.exists(samples)]
df <- lapply(samples, read_tsv)
outfile <- join_all(df, by = "geneid")
dir.create("counts",showWarnings = FALSE)
write_tsv(outfile,"counts/raw_counts.tsv", col_names = TRUE)
RSCRIPT
